apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::007743985928:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-14M76SKJTFXJ9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::007743985928:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-07T18:22:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "931"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c210aa9e-78fc-11ea-9b95-0edf5d393a43